name: Tests

on: [push]

jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows/Static/X64/Release",
            os: windows-2019,
            config: Release,
            args: -G Ninja,
          }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.28'

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Released
